'use strict';
const KEYS=['uefa','sofascore','flashscore','opta'];
const NAMES={uefa:'UEFA',sofascore:'Sofascore',flashscore:'Flashscore',opta:'Opta Analyst'};
const COLORS={uefa:'#68b7ff',sofascore:'#beabff',flashscore:'#ffae74',opta:'#77e4c5'};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'N/D':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3}).format(n);
let DATA,PAGE=1;const PAGE_SIZE=80;const editorial=()=>$('#editorial').checked;
function currentCell(row,k){let c=row.values[k];if(k==='sofascore'&&editorial()&&(!c||c.value==null))c=row.editorial;return c||null}
function usable(c){return c&&c.comparable&&c.period==='ALL'&&typeof c.value==='number'&&Number.isFinite(c.value)&&(c.evidence==='direct'||(editorial()&&c.evidence==='editorial'))}
function cmp(a,b){if(!Number.isFinite(a)||!Number.isFinite(b))return null;let d=b-a;return{delta:d,absolute:Math.abs(d),relative:a?Math.abs(d)/Math.abs(a)*100:(b===0?0:null),different:Math.abs(d)>1e-9}}
function cellCmp(a,b){const v=cmp(a.value,b.value);if(!v)return null;let compatible=false;if(v.different&&a.unit==='%'&&b.unit==='%'&&(a.precision||0)!==(b.precision||0)){const [lo,hi]=(a.precision||0)<(b.precision||0)?[a,b]:[b,a];const scale=10**(lo.precision||0);compatible=Math.abs(Math.round(hi.value*scale)/scale-lo.value)<1e-9}return {...v,precision_compatible:compatible}}
function pairHTML(row){const out=[];for(let i=0;i<KEYS.length;i++)for(let j=i+1;j<KEYS.length;j++){const a=currentCell(row,KEYS[i]),b=currentCell(row,KEYS[j]);if(a?.value==null||b?.value==null)continue;const v=cellCmp(a,b),valid=usable(a)&&usable(b);out.push(`<li>${NAMES[KEYS[i]]} → ${NAMES[KEYS[j]]}: Δ ${v.delta>0?'+':''}${fmt(v.delta)}${a.unit==='%'?' p.p.':''}; |Δ| ${fmt(v.absolute)}; desvio ${v.relative==null?'indefinido (base zero)':fmt(v.relative)+'%'}${v.precision_compatible?' · compatível com arredondamento':''}${valid?'':' · comparação numérica exploratória, definição/escopo pendente'}</li>`)}return out.length?`<details class=pair-details><summary>Diferenças absolutas e relativas entre todos os pares disponíveis</summary><ul>${out.join('')}</ul></details>`:''}
function rowDiff(row){const cells=KEYS.map(k=>currentCell(row,k)).filter(usable);return cells.some((a,i)=>cells.slice(i+1).some(b=>cmp(a.value,b.value).different))}
function rowSensitive(row){const c=KEYS.map(k=>currentCell(row,k)).filter(x=>x&&typeof x.value==='number');return !rowComparable(row)&&c.some((a,i)=>c.slice(i+1).some(b=>cmp(a.value,b.value).different))}
function rowComparable(row){let n=KEYS.filter(k=>usable(currentCell(row,k))).length;return n>=2}
function aggregate(matches,a,b){let compared=0,different=0,rounding=0,games=new Set();for(const m of matches)for(const r of m.rows){const ca=currentCell(r,a),cb=currentCell(r,b);if(!usable(ca)||!usable(cb))continue;compared++;const v=cellCmp(ca,cb);rounding+=Number(v.precision_compatible);if(v.different){different++;games.add(m.id)}}return{compared,different,rate:compared?different/compared*100:null,games:games.size,rounding,other:different-rounding}}
function status(s){const st=s?.status||'not_available';const text={collected:'Coletado',partial:'Parcial',editorial_only:'Só editorial',index_only:'Só índice',blocked:'Bloqueado',not_available:'Não disponível',not_found:'Não localizado',not_covered:'Sem cobertura',identity_only:'Só identidade'}[st]||st;return `<span class="badge ${st==='collected'?'ok':st==='partial'||st==='editorial_only'?'partial':'empty'}">${esc(text)}</span>`}
function coverage(){const total=DATA.matches.length;$('#coverage').innerHTML=KEYS.map(k=>{let direct=DATA.matches.filter(m=>m.rows.some(r=>r.values[k]?.evidence==='direct'&&r.values[k]?.value!=null)).length;let ed=DATA.matches.filter(m=>m.rows.some(r=>k==='sofascore'&&r.editorial?.value!=null)).length;return `<article class="source-card" style="--source-color:${COLORS[k]}"><div>${NAMES[k]}</div><strong>${direct}<span class="muted"> / ${total}</span></strong><p>jogos com algum dado direto${ed?` · ${ed} com dados editoriais separados`:''}</p><p>${esc(DATA.sources[k].description)}</p></article>`}).join('')}
function pairs(){let html='';for(let i=0;i<KEYS.length;i++)for(let j=i+1;j<KEYS.length;j++){const a=KEYS[i],b=KEYS[j],v=aggregate(DATA.matches,a,b);html+=`<div class="pair"><div>${NAMES[a]} × ${NAMES[b]}</div><strong class="rate">${v.rate==null?'Não calculável':fmt(v.rate)+'%'}</strong><span>${v.different} diferenças / ${v.compared} células comparáveis<br>${v.games} jogos com diferença<br>${v.rounding} compatíveis com arredondamento · ${v.other} demais diferenças<br>${editorial()?'inclui editorial quando disponível':'apenas dados diretos'}</span></div>`}$('#pairs').innerHTML=html}
function inventory(){ $('#inventory tbody').innerHTML=DATA.matches.map(m=>{let n=0,d=0;for(const k of KEYS.slice(1)){let s=aggregate([m],'uefa',k);n+=s.compared;d+=s.different}return `<tr><td><div class="date">${esc(m.date)} · ${esc(m.group)}</div><button class="match-link" data-game="${esc(m.id)}">${esc(m.home)} ${esc(m.score)} ${esc(m.away)}</button></td>${KEYS.map(k=>`<td>${status(m.sources[k])}</td>`).join('')}<td>${n?`<b>${d} / ${n}</b><br>${fmt(d/n*100)}%`:'Não calculável'}</td></tr>`}).join('');document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{$('#game').value=b.dataset.game;resetExplore();$('#comparison').scrollIntoView({behavior:'smooth'})})}
function cellHTML(row,k,max){const c=currentCell(row,k),base=currentCell(row,'uefa');let shown=c?.value!=null,metric=DATA.metrics[row.metric]||{};let unit=metric.unit||'';let difftext='Sem par comparável com a UEFA',different=false;
 if(k==='uefa')difftext='Base de referência, não padrão de verdade';else if(usable(base)&&usable(c)){let v=cellCmp(base,c);different=v.different;difftext=`Δ ${v.delta>0?'+':''}${fmt(v.delta)}${unit==='%'?' p.p.':''} · |Δ| ${fmt(v.absolute)}<br>Desvio relativo: ${v.relative==null?'indefinido (base zero)':fmt(v.relative)+'%'}${v.precision_compatible?'<br>Compatível com arredondamento':''}`}
 let evidence=shown?({direct:'Dado direto',editorial:'Artigo — não é a aba',index:'Só índice — excluído',conflicting:'Contradição — excluído'}[c.evidence]||c.evidence):'Não disponível';
 if(shown&&c.layer)evidence+=' · '+(c.layer==='widget'?'Match Centre':c.layer==='feed_matchstats_detailed'?'feed público detalhado':c.layer==='feed_matchexpectedgoals'?'feed público xG':c.layer);
 if(shown&&!c.comparable)evidence+=' · definição/período não comparável';
 const link=c?.url?`<a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">Fonte ↗</a>`:'';
 return `<div class="value-col" style="--source-color:${COLORS[k]}"><div class="source-name">${NAMES[k]}</div><div class="number">${shown?fmt(c.value)+(unit==='%'?'%':''):'—'}</div><div class="bar-track"><div class="bar" style="width:${shown&&max?Math.min(100,Math.abs(c.value)/max*100):0}%"></div></div><div class="delta ${different?'diff':''}">${difftext}</div><div class="evidence">${esc(evidence)} ${link}</div></div>`}
function explore(){
 const id=$('#game').value,term=$('#metric').value.trim().toLocaleLowerCase('pt-BR'),mode=$('#mode').value;
 const matches=id==='all'?DATA.matches:DATA.matches.filter(m=>m.id===id);
 const groups=matches.map(m=>({m,rows:m.rows.filter(r=>{
  const meta=DATA.metrics[r.metric]||{};
  return (!term||[meta.label,r.metric,r.team==='home'?m.home:m.away].join(' ').toLocaleLowerCase('pt-BR').includes(term))&&(mode==='all'||(mode==='different'?rowDiff(r):mode==='sensitive'?rowSensitive(r):rowComparable(r)))
 })}));
 const total=groups.reduce((n,g)=>n+g.rows.length,0),pages=Math.max(1,Math.ceil(total/PAGE_SIZE));PAGE=Math.min(Math.max(1,PAGE),pages);
 const from=(PAGE-1)*PAGE_SIZE,to=from+PAGE_SIZE;let cursor=0,visible=0;
 const html=groups.map(({m,rows})=>{
  const start=cursor;cursor+=rows.length;
  const slice=rows.slice(Math.max(0,from-start),Math.max(0,to-start));
  if(!slice.length&&id==='all')return '';visible+=slice.length;
  const cards=slice.map(r=>{
   const meta=DATA.metrics[r.metric]||{},max=Math.max(0,...KEYS.map(k=>Math.abs(currentCell(r,k)?.value||0)));
   return `<article class="metric-card"><div class="metric-name"><b>${esc(meta.label||r.metric)}${meta.unit&&meta.unit!=='%'?' ('+esc(meta.unit)+')':''}</b><span class="metric-team">${esc(r.team==='home'?m.home:m.away)} · ${esc(meta.period||'Jogo completo')}</span></div><div class="columns">${KEYS.map(k=>cellHTML(r,k,max)).join('')}</div>${pairHTML(r)}</article>`
  }).join('');
  const links=KEYS.map(k=>m.sources[k]?.url?`<a href="${esc(m.sources[k].url)}" target="_blank" rel="noopener noreferrer">${NAMES[k]} ↗</a>`:`${NAMES[k]}: sem fonte validada`).join(' · ');
  return `<section class="match-section" data-match-id="${esc(m.id)}"><h3>${esc(m.home)} ${esc(m.score)} ${esc(m.away)}</h3><div class="muted">${esc(m.date)} · ${esc(m.group)} · UEFA ${esc(m.id)}</div><div class="source-links">${links}</div>${m.notes?.length?`<p class="notes">${m.notes.map(esc).join(' ')}</p>`:''}<p class="count-caption">${rows.length} linhas desta partida no filtro; ${slice.length} nesta página</p>${cards||'<div class="no-data">Nenhuma linha atende ao filtro. Isso não prova igualdade das fontes. Verifique a cobertura ou selecione “Todos os indicadores do painel”.</div>'}</section>`
 }).join('');
 $('#explorer').innerHTML=`<div class="pagination"><button id="prev-page" ${PAGE<=1?'disabled':''}>← Anterior</button><span>${total} linhas no filtro · página ${PAGE} de ${pages} · ${visible} exibidas</span><button id="next-page" ${PAGE>=pages?'disabled':''}>Próxima →</button></div>`+(html||'<div class="no-data">Nenhuma diferença comparável neste filtro. Ausência não comprova igualdade.</div>');
 $('#explorer').dataset.visibleRows=String(visible);$('#explorer').dataset.totalRows=String(total);
 $('#prev-page').onclick=()=>{PAGE--;explore();$('#comparison').scrollIntoView()};$('#next-page').onclick=()=>{PAGE++;explore();$('#comparison').scrollIntoView()};
}
function resetExplore(){PAGE=1;explore()}
function download(){let lines=[['uefa_id','date','home','away','metric','team','source','value','unit','evidence','comparable','delta_vs_uefa','absolute_delta','relative_pct','url']];for(const m of DATA.matches)for(const r of m.rows)for(const k of KEYS){const c=currentCell(r,k);if(!c)continue;let base=currentCell(r,'uefa'),d=usable(base)&&usable(c)?cmp(base.value,c.value):null;lines.push([m.id,m.date,m.home,m.away,r.metric,r.team==='home'?m.home:m.away,k,c.value,DATA.metrics[r.metric]?.unit||'',c.evidence,!!c.comparable,d?.delta??'',d?.absolute??'',d?.relative??'',c.url||''])}let text='\uFEFF'+lines.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='nations-league-observacoes.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function init(){try{const response=await fetch('data.json');if(!response.ok)throw Error(`HTTP ${response.status}`);DATA=await response.json();window.AUDIT_DATA=DATA;$('#stamp').textContent=`Corte: ${DATA.meta.cutoff} · ${DATA.matches.length} jogos encerrados · Emitido: ${DATA.meta.generated_at}`;$('#limitation').textContent=DATA.meta.limitations;coverage();$('#game').innerHTML='<option value="all">Todos os jogos do corte</option>'+DATA.matches.map(m=>`<option value="${esc(m.id)}">${esc(m.date)} · ${esc(m.home)} ${esc(m.score)} ${esc(m.away)}</option>`).join('');$('#game').value='2047924';$('#recommendation').innerHTML=`<div class="recommend">${DATA.recommendation.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div><ul>${DATA.recommendation.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></li>`).join('')}</ul>`;$('#method').innerHTML='<ul>'+DATA.meta.method.map(t=>`<li>${esc(t)}</li>`).join('')+'</ul>';pairs();inventory();explore();$('#editorial').onchange=()=>{pairs();inventory();explore()};$('#game').onchange=resetExplore;$('#mode').onchange=resetExplore;$('#metric').oninput=resetExplore;$('#download').onclick=download;document.body.dataset.loaded='true'}catch(e){$('#limitation').textContent='Falha ao carregar a base. Nenhum número foi substituído ou simulado: '+e.message;document.body.dataset.loaded='error';console.error(e)}}
init();
